runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: yarn config set nodeLinker pno
      shell: bash

    - run: yarn install --no-immutable
      shell: bash
