runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: corepack enable
      shell: bash

    - run: yarn config set nodeLinker node-modules
      shell: bash

    - run: yarn install --no-immutable
      shell: bash
